### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by Technikte** [xsteadfastx/iperf3exporter#1]
Hallo,
das fertige Docker image sieht sehr viel versprechend aus und daher wollte ich es mal ausprobieren, aber scheite daran mir das image zu pullen..
Der Fehler "keine Berechtigung" tritt mit allen Versionen auf.

```
root@xxx:~# docker pull ghcr.io/xsteadfastx/iperf3exporter:0.2.0
Error response from daemon: Head "https://ghcr.io/v2/xsteadfastx/iperf3exporter/manifests/0.2.0": unauthorized
```

**Comment by xsteadfastx** [comment]
hi,

On Do, 18. Nov 03:09, Technikte wrote:
> ***@***.***:~# docker pull ghcr.io/xsteadfastx/iperf3exporter:0.2.0
> Error response from daemon: Head "https://ghcr.io/v2/xsteadfastx/iperf3exporter/manifests/0.2.0": unauthorized

anscheinend muss man um ghcr packages zu nutzen, sich damit auch per
docker anmelden. ich dachte die sind einfach public available. das darf
eigentlich nicht sein. ich suche mal...

**Comment by xsteadfastx** [comment]
sooo.... bitte nochmal probieren. das war auf private gesetzt. sollte nun gehen!

**Comment by Technikte** [comment]
Problem gelöst. Vielen Dank für das sehr schnelle beheben !
```
root@xxx:~# docker pull ghcr.io/xsteadfastx/iperf3exporter:v0.2.1
v0.2.1: Pulling from xsteadfastx/iperf3exporter
97518928ae5f: Pull complete 
00d76844a9f7: Pull complete 
c5113ef37314: Pull complete 
Digest: sha256:2310cf6ba68d1b26629acf084df89a4241adf043142eb78331d6c6062748e5b7
Status: Downloaded newer image for ghcr.io/xsteadfastx/iperf3exporter:v0.2.1
ghcr.io/xsteadfastx/iperf3exporter:v0.2.1
```
