### ISSUE TITLE
[Question] Error: could not get upload metrics

### ISSUE THREAD

**Issue by Technikte** [xsteadfastx/iperf3exporter#3]
Hi again,
your work is pretty nice but I have a problem to run the container 24/7 to monitor the speed.
I will attach the logs from the server side (hosted at netcup.de) and client side (my local cable connection).
Maybe some wait time between the Download and Upload Speed test would help but I am not quite sure about that.

I did the test with --time-skew-threshold and without but nothing changed...on the other hand manual test from work desktop worked every time. I think something in my home network (maybe my firewall or so) is the cause, do you have any idea what it could be ?

> xsteadfastx/iperf3exporter:0.3.0

> [root@xxx ~]# iperf3 -v
> iperf 3.10.1 (cJSON 1.7.13)
> Linux vxxx 5.14.16-arch1-1 #1 SMP PREEMPT Tue, 02 Nov 2021 22:22:59 +0000 x86_64
> Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication, bind to device, support IPv4 don't fragment

```
[root@xxx ~]# iperf3 -s -p 52001 --time-skew-threshold 30
-----------------------------------------------------------
Server listening on 52001 (test #1)
-----------------------------------------------------------
Accepted connection from 31.xx.xxx.xx, port 32284
[  5] local 94.xx.xxx.xx port 52001 connected to 31.xx.xxx.xx port 43051
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  3.14 MBytes  26.3 Mbits/sec    0    164 KBytes       
[  5]   1.00-2.00   sec  11.6 MBytes  97.4 Mbits/sec    0    642 KBytes       
[  5]   2.00-3.00   sec  36.2 MBytes   304 Mbits/sec    0   1.97 MBytes       
[  5]   3.00-4.00   sec  33.8 MBytes   283 Mbits/sec  250   1.58 MBytes       
[  5]   4.00-5.00   sec  43.8 MBytes   367 Mbits/sec    0   1.71 MBytes       
[  5]   5.00-6.00   sec  36.2 MBytes   304 Mbits/sec   78   1.28 MBytes       
[  5]   6.00-7.00   sec  35.0 MBytes   293 Mbits/sec    0   1.35 MBytes       
[  5]   7.00-8.00   sec  40.0 MBytes   336 Mbits/sec    0   1.41 MBytes       
[  5]   8.00-9.00   sec  41.2 MBytes   346 Mbits/sec    0   1.44 MBytes       
[  5]   9.00-10.00  sec  43.8 MBytes   367 Mbits/sec    0   1.47 MBytes       
[  5]  10.00-10.03  sec  1.25 MBytes   394 Mbits/sec    0   1.47 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.03  sec   326 MBytes   273 Mbits/sec  328             sender
-----------------------------------------------------------
Server listening on 52001 (test #2)
-----------------------------------------------------------



11:15AM INF drone/src/main.go:43 > starting... listen=0.0.0.0:9093
11:18AM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.4:57084 request-url=/probe?target=94.xx.xxx.xx%3A52001 user-agent=Prometheus/2.31.1 uuid=16f5d1a8-b6c4-4a06-b2e4-c281f807c24b
11:18AM DBG drone/src/main.go:253 > extracted target from url params trgt=94.xx.xxx.xx:52001 uuid=16f5d1a8-b6c4-4a06-b2e4-c281f807c24b
11:18AM INF drone/src/main.go:265 > getting download metrics uuid=16f5d1a8-b6c4-4a06-b2e4-c281f807c24b
11:18AM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c 94.xx.xxx.xx -p 52001 -t 10 -R" uuid=16f5d1a8-b6c4-4a06-b2e4-c281f807c24b
11:18AM INF drone/src/main.go:274 > getting upload metrics uuid=16f5d1a8-b6c4-4a06-b2e4-c281f807c24b
11:18AM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c 94.xx.xxx.xx -p 52001 -t 10" uuid=16f5d1a8-b6c4-4a06-b2e4-c281f807c24b
11:18AM DBG drone/src/main.go:180 > output from failed run stderr= stdout="{\n\t\"start\":\t{\n\t\t\"connected\":\t[],\n\t\t\"version\":\t\"iperf 3.10.1\",\n\t\t\"system_info\":\t\"Linux ByteNet 5.14.15-Unraid #1 SMP Thu Oct 28 09:56:33 PDT 2021 x86_64\"\n\t},\n\t\"intervals\":\t[],\n\t\"end\":\t{\n\t},\n\t\"error\":\t\"error - unable to receive control message: Connection reset by peer\"\n}\n" uuid=16f5d1a8-b6c4-4a06-b2e4-c281f807c24b

11:18AM ERR drone/src/main.go:277 > could not create upload metrics error="could not get upload metrics: could not run command: exit status 1" uuid=16f5d1a8-b6c4-4a06-b2e4-c281f807c24b
```

EDIT: I can't repeat it by hand, even if I start test quickly after each other. So slowly I run out of ideas at the point.
Maybe you can help or have another idea?
With the wobcom endpoint it seems to work most of the time.

**Comment by Technikte** [comment]
An other example log.. sometimes it failed with wobcom.. and I dont really know why.

```
9:48PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34146 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=86a796c9-6b69-4cd5-863d-c097f2658631
9:48PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=86a796c9-6b69-4cd5-863d-c097f2658631
9:48PM INF drone/src/main.go:265 > getting download metrics uuid=86a796c9-6b69-4cd5-863d-c097f2658631
9:48PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=86a796c9-6b69-4cd5-863d-c097f2658631
9:48PM INF drone/src/main.go:274 > getting upload metrics uuid=86a796c9-6b69-4cd5-863d-c097f2658631
9:48PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=86a796c9-6b69-4cd5-863d-c097f2658631
9:49PM INF drone/src/main.go:283 > done scraping uuid=86a796c9-6b69-4cd5-863d-c097f2658631
9:58PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34148 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
9:58PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
9:58PM INF drone/src/main.go:265 > getting download metrics uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
9:58PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
9:58PM INF drone/src/main.go:274 > getting upload metrics uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
9:58PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
9:58PM DBG drone/src/main.go:180 > output from failed run stderr= stdout="{\n\t\"start\":\t{\n\t\t\"connected\":\t[],\n\t\t\"version\":\t\"iperf 3.10.1\",\n\t\t\"system_info\":\t\"Linux f56d01ea9b84 5.14.15-Unraid #1 SMP Thu Oct 28 09:56:33 PDT 2021 x86_64\"\n\t},\n\t\"intervals\":\t[],\n\t\"end\":\t{\n\t},\n\t\"error\":\t\"error - unable to connect to server: Connection refused\"\n}\n" uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77

9:58PM ERR drone/src/main.go:277 > could not create upload metrics error="could not get upload metrics: could not run command: exit status 1" uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
10:08PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34150 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:08PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:08PM INF drone/src/main.go:265 > getting download metrics uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:08PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:08PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34150 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:08PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:08PM INF drone/src/main.go:265 > getting download metrics uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:08PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:08PM INF drone/src/main.go:274 > getting upload metrics uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:08PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:09PM INF drone/src/main.go:283 > done scraping uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:09PM INF drone/src/main.go:283 > done scraping uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
10:18PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34152 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
10:18PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
10:18PM INF drone/src/main.go:265 > getting download metrics uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
10:18PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
10:18PM INF drone/src/main.go:274 > getting upload metrics uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
10:18PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
10:18PM DBG drone/src/main.go:180 > output from failed run stderr= stdout="{\n\t\"start\":\t{\n\t\t\"connected\":\t[],\n\t\t\"version\":\t\"iperf 3.10.1\",\n\t\t\"system_info\":\t\"Linux f56d01ea9b84 5.14.15-Unraid #1 SMP Thu Oct 28 09:56:33 PDT 2021 x86_64\"\n\t},\n\t\"intervals\":\t[],\n\t\"end\":\t{\n\t},\n\t\"error\":\t\"error - unable to receive control message: Connection reset by peer\"\n}\n" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e

10:18PM ERR drone/src/main.go:277 > could not create upload metrics error="could not get upload metrics: could not run command: exit status 1" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
10:18PM DBG drone/src/main.go:180 > output from failed run stderr= stdout="{\n\t\"start\":\t{\n\t\t\"connected\":\t[],\n\t\t\"version\":\t\"iperf 3.10.1\",\n\t\t\"system_info\":\t\"Linux f56d01ea9b84 5.14.15-Unraid #1 SMP Thu Oct 28 09:56:33 PDT 2021 x86_64\"\n\t},\n\t\"intervals\":\t[],\n\t\"end\":\t{\n\t},\n\t\"error\":\t\"error - unable to receive control message: Connection reset by peer\"\n}\n" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e

10:18PM ERR drone/src/main.go:277 > could not create upload metrics error="could not get upload metrics: could not run command: exit status 1" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
10:28PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34154 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
10:28PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
10:28PM INF drone/src/main.go:265 > getting download metrics uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
10:28PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
10:28PM INF drone/src/main.go:274 > getting upload metrics uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
10:28PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
10:29PM INF drone/src/main.go:283 > done scraping uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
```

**Comment by xsteadfastx** [comment]
connection reset by peer. i dont really know if this is really a problem with the exporter itself. as you say... maybe with a second wait in between upload and download tasks. i will run it locally and see if i can reproduce this behavior.

**Comment by Technikte** [comment]
Some slightly different error..running test @ 10min intervall for 10s over some hours..
Prometheus errors with..

> server returned HTTP status 500 Internal Server Error

> IPERF3EXPORTER_EXPORTER_TIMEOUT=1m
> IPERF3EXPORTER_IPERF3_TIME=10


```
8:38PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34744 request-url=/probe?target=xxx.yyy.de%3A56378 user-agent=Prometheus/2.31.1 uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff
8:38PM DBG drone/src/main.go:253 > extracted target from url params trgt=xxx.yyy.de:56378 uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff
8:38PM INF drone/src/main.go:265 > getting download metrics uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff
8:38PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c xxx.yyy.de -p 56378 -t 10 -R" uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff
8:38PM INF drone/src/main.go:274 > getting upload metrics uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff
8:38PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c xxx.yyy.de -p 56378 -t 10" uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff
8:39PM DBG drone/src/main.go:180 > output from failed run stderr= stdout= uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff

8:39PM ERR drone/src/main.go:277 > could not create upload metrics error="could not get upload metrics: could not run command: signal: killed" uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff

8:39PM DBG drone/src/main.go:180 > output from failed run stderr= stdout= uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff

8:39PM ERR drone/src/main.go:277 > could not create upload metrics error="could not get upload metrics: could not run command: signal: killed" uuid=28ef1ac6-1c9e-4b4a-be07-3f078e8841ff
```

**Comment by xsteadfastx** [comment]
signal killed sounds strange. do you run this with systemd? do you run this against a local server or something? or always in the internet? i think its not so uncommon that a iperf3 server is not availabe and it just fails.

**Comment by xsteadfastx** [comment]
> An other example log.. sometimes it failed with wobcom.. and I dont really know why.
> 
> ```
> 9:48PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34146 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=86a796c9-6b69-4cd5-863d-c097f2658631
> 9:48PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=86a796c9-6b69-4cd5-863d-c097f2658631
> 9:48PM INF drone/src/main.go:265 > getting download metrics uuid=86a796c9-6b69-4cd5-863d-c097f2658631
> 9:48PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=86a796c9-6b69-4cd5-863d-c097f2658631
> 9:48PM INF drone/src/main.go:274 > getting upload metrics uuid=86a796c9-6b69-4cd5-863d-c097f2658631
> 9:48PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=86a796c9-6b69-4cd5-863d-c097f2658631
> 9:49PM INF drone/src/main.go:283 > done scraping uuid=86a796c9-6b69-4cd5-863d-c097f2658631
> 9:58PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34148 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
> 9:58PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
> 9:58PM INF drone/src/main.go:265 > getting download metrics uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
> 9:58PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
> 9:58PM INF drone/src/main.go:274 > getting upload metrics uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
> 9:58PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
> 9:58PM DBG drone/src/main.go:180 > output from failed run stderr= stdout="{\n\t\"start\":\t{\n\t\t\"connected\":\t[],\n\t\t\"version\":\t\"iperf 3.10.1\",\n\t\t\"system_info\":\t\"Linux f56d01ea9b84 5.14.15-Unraid #1 SMP Thu Oct 28 09:56:33 PDT 2021 x86_64\"\n\t},\n\t\"intervals\":\t[],\n\t\"end\":\t{\n\t},\n\t\"error\":\t\"error - unable to connect to server: Connection refused\"\n}\n" uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
> 
> 9:58PM ERR drone/src/main.go:277 > could not create upload metrics error="could not get upload metrics: could not run command: exit status 1" uuid=f41c56d0-a7ef-44f6-ac00-fc3623f52e77
> 10:08PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34150 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:08PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:08PM INF drone/src/main.go:265 > getting download metrics uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:08PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:08PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34150 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:08PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:08PM INF drone/src/main.go:265 > getting download metrics uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:08PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:08PM INF drone/src/main.go:274 > getting upload metrics uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:08PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:09PM INF drone/src/main.go:283 > done scraping uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:09PM INF drone/src/main.go:283 > done scraping uuid=aa8e78de-e2ec-45c2-bf67-8493252ffdad
> 10:18PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34152 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 10:18PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 10:18PM INF drone/src/main.go:265 > getting download metrics uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 10:18PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 10:18PM INF drone/src/main.go:274 > getting upload metrics uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 10:18PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 10:18PM DBG drone/src/main.go:180 > output from failed run stderr= stdout="{\n\t\"start\":\t{\n\t\t\"connected\":\t[],\n\t\t\"version\":\t\"iperf 3.10.1\",\n\t\t\"system_info\":\t\"Linux f56d01ea9b84 5.14.15-Unraid #1 SMP Thu Oct 28 09:56:33 PDT 2021 x86_64\"\n\t},\n\t\"intervals\":\t[],\n\t\"end\":\t{\n\t},\n\t\"error\":\t\"error - unable to receive control message: Connection reset by peer\"\n}\n" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 
> 10:18PM ERR drone/src/main.go:277 > could not create upload metrics error="could not get upload metrics: could not run command: exit status 1" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 10:18PM DBG drone/src/main.go:180 > output from failed run stderr= stdout="{\n\t\"start\":\t{\n\t\t\"connected\":\t[],\n\t\t\"version\":\t\"iperf 3.10.1\",\n\t\t\"system_info\":\t\"Linux f56d01ea9b84 5.14.15-Unraid #1 SMP Thu Oct 28 09:56:33 PDT 2021 x86_64\"\n\t},\n\t\"intervals\":\t[],\n\t\"end\":\t{\n\t},\n\t\"error\":\t\"error - unable to receive control message: Connection reset by peer\"\n}\n" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 
> 10:18PM ERR drone/src/main.go:277 > could not create upload metrics error="could not get upload metrics: could not run command: exit status 1" uuid=f3e2c8a0-500f-41fa-8057-07f64d7b8b0e
> 10:28PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:34154 request-url=/probe?target=speedtest.wobcom.de user-agent=Prometheus/2.31.1 uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
> 10:28PM DBG drone/src/main.go:253 > extracted target from url params trgt=speedtest.wobcom.de uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
> 10:28PM INF drone/src/main.go:265 > getting download metrics uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
> 10:28PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10 -R" uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
> 10:28PM INF drone/src/main.go:274 > getting upload metrics uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
> 10:28PM DBG drone/src/main.go:169 > created command cmd="/usr/bin/iperf3 -J -c speedtest.wobcom.de -p 5201 -t 10" uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
> 10:29PM INF drone/src/main.go:283 > done scraping uuid=117f04cf-26d8-4fec-b05f-4578812f25a9
> ```

i discovered manually that it just sometimes fails. iperf3 server can take one request at a time i think. if there is a other client doing the test... it will fail.

**Comment by xsteadfastx** [comment]
i released 0.4.0 with an error counter metric. just to monitoring this errors.

**Comment by Technikte** [comment]
> signal killed sounds strange. do you run this with systemd? do you run this against a local server or something? or always in the internet? i think its not so uncommon that a iperf3 server is not availabe and it just fails.

Well, I am running the server side via systemd (like described here https://www.chaoticum.ch/technisches/iperf) at a vserver from netcup.de and I am the only one who is using it. I know that on public server it can happen that another test from someone else is running..

All error always pops up after the first test which is the download one (-R) and then the other one fails. Maybe changing the order of up-/download and/or a delay in between would help or change something.

**Comment by xsteadfastx** [comment]
check for version 0.5.0. this has a configurable wait time between scrapes. maybe this can help debug...

**Comment by Technikte** [comment]
Thanks for the new version 👍 
For now, I ran already 2h with the update and no test failed yet, it seems even the default delay of 1000ms is enough.
I will monitor it longer to be safe ;)

**Comment by xsteadfastx** [comment]
cant wait to hear about if this fixed this in a long term :)

**Comment by Technikte** [comment]
![image](https://user-images.githubusercontent.com/49494924/143097715-fe47f80e-e1b1-4af8-b709-a7d65ce92eb0.png)
As you can see in the screenshot, some ~4 tests failed and no numbers got scraped..

The error I got in the log shows that it failed right at the start for the test and not anymore between the download and upload.
For the moment I would not consider this a major issue, so I can live with that and so I will close this issue..the "new" issue with failed starts could be tracked in a newly created issue for better separation.
To fix this maybe some kind of retry mechanism would be needed.


```
12:48PM INF drone/src/vendor/go.xsfx.dev/logginghandler/logginghandler.go:38 > method=GET proto=HTTP/1.1 referer= remote=172.17.0.1:53756 request-url=/probe?target=xxx.yyy.de%3A56378 user-agent=Prometheus/2.31.1 uuid=628808c0-6625-4a8d-add7-b0c48647cc55
12:48PM DBG drone/src/main.go:256 > extracted target from url params trgt=xxx.yyy.de:56378 uuid=628808c0-6625-4a8d-add7-b0c48647cc55
12:48PM INF drone/src/main.go:269 > getting download metrics uuid=628808c0-6625-4a8d-add7-b0c48647cc55
12:48PM DBG drone/src/main.go:172 > created command cmd="/usr/bin/iperf3 -J -c xxx.yyy.de -p 56378 -t 10 -R" uuid=628808c0-6625-4a8d-add7-b0c48647cc55
12:49PM DBG drone/src/main.go:183 > output from failed run stderr= stdout= uuid=628808c0-6625-4a8d-add7-b0c48647cc55

12:49PM ERR drone/src/main.go:273 > could not create download metrics error="could not get download metrics: could not run command: signal: killed" uuid=628808c0-6625-4a8d-add7-b0c48647cc55
```
